### ISSUE TITLE
Spicetify apply returns "error Cannot find symbol for Custom app React symbols"

### ISSUE THREAD

**Issue by Moquent** [spicetify/spicetify-cli#1515]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows
1.1.80.699.gc3dac750

- Spicetify version: 2.9.1
```

### 📝 Description

Spicetify doesn't work.
When I run the spicetify apply command it should apply all the extensions and themes, instead it gives me the error which many others have also opened an issue for. I've tried reinstalling Spotify and Spicetify but it still doesn't work.

It's probably because of a new update... Spotify functions normally.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/63721912/156542192-c67301ef-0c95-4606-b529-90f9ab293908.png)

**Comment by xerta555** [comment]
I get almost same issue with the last update of spotify.
Custom app(s) don't works.
![image](https://user-images.githubusercontent.com/20888017/156549210-c6759dab-51a4-4142-b807-38f32c36a2c1.png)

**Comment by Mahas1** [comment]
Same here. I'm guessing whoever wrote the code accidentally hardcoded their directory paths, hence the `C:/Users/Afonso`
Here is my error message, for comparison.

```
PS C:\Users\mahas> spicetify backup apply
spicetify v2.9.1
info spicetify up-to-date
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc001206000, 0x205807, 0x205807, 0xc001206000)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:215 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc00000d940, 0x38, 0xc00011d910)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/utils.go:191 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc00000d940, 0x38, 0xc00004c4a0, 0x2, 0x2, 0xc00004c4c0, 0x2, 0x2, 0x10101, 0x4d8d14, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:188 +0xc5
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000aae0, 0x2b, 0xc00004c4a0, 0x2, 0x2, 0xc00004c4c0, 0x2, 0x2, 0x10101, 0x4d8d14, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:37 +0x57d
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x4d8d14, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/apply.go:72 +0x68c
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:194 +0x4f9
PS C:\Users\mahas>
```

**Comment by bzzrak** [comment]
Exact same issue here
```
Fetch latest release info:
OK
info Current version: 2.9.0
info Latest release: 2.9.1
Downloading:
OK
Extracting:
OK
success spicetify is up-to-date.
info Please run "spicetify restore backup apply" to receive new features and bug fixes
spicetify v2.9.1
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Err
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc0010cc000, 0x205807, 0x205807, 0xc0010cc000)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:215 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc00000c1c0, 0x39, 0xc0000d5910)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/utils.go:191 +0xdb                                                              github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc00000c1c0, 0x39, 0xc0004f60a0, 0x1, 0x2, 0xc0004f60c0, 0x1, 0x2, 0x10101, 0xbf8d14, ...)                                                                                                                                C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:188 +0xc5                                                              github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000eba0, 0x2c, 0xc0004f60a0, 0x1, 0x2, 0xc0004f60c0, 0x1, 0x2, 0x10101, 0xbf8d14, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:37 +0x57d
github.com/khanhas/spicetify-cli/src/cmd.Apply(0xbf8d14, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/apply.go:72 +0x68c
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:194 +0x4f9
success Config changed: current_theme = SpotifyNoPremium
info Run "spicetify apply" to apply new config
warning Config "extensions" unchanged: fullappdisplay.js is already in the list.
warning Config "custom_apps" unchanged: lyrics-plus is already in the list.                                                            spicetify v2.9.1                                                                                                                       Err                                                                                                                                    Overwriting themed assets:                                                                                                             OK                                                                                                                                     Transferring user.css:                                                                                                                 OK                                                                                                                                     Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc000806000, 0x205807, 0x205807, 0xc000806000)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:215 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc00000cdc0, 0x39, 0xc000511910)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/utils.go:191 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc00000cdc0, 0x39, 0xc0000a66c0, 0x1, 0x2, 0xc0000a6780, 0x1, 0x2, 0x10101, 0xc0000acad1, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:188 +0xc5
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000c2930, 0x2c, 0xc0000a66c0, 0x1, 0x2, 0xc0000a6780, 0x1, 0x2, 0x10101, 0xc0000acad1, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:37 +0x57d
github.com/khanhas/spicetify-cli/src/cmd.Apply(0xbf8d14, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/apply.go:72 +0x68c
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:194 +0x4f9
```
