### ISSUE TITLE
Gray Screen

### ISSUE THREAD

**Issue by ruizlenato** [spicetify/spicetify-cli#1684]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85.895.g2a71e1b8
- Spicetify version:  2.9.8
- OS: Windows 11
```

### 📝 Description

When I open Spotify after applying Spicetify on Spotify it opens with a gray screen.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/49354525/169167766-4e3c05ec-8478-41b4-8015-160cd2ee7e43.png)

**Comment by Im-Kal** [comment]
Also is there any output when you apply Spicetify? Does it show ```error: cannot find symbol for Custom app React Element ```?

**Comment by BetTD** [comment]
Same issue here, it does show the error you mentioned @Im-Kal 

```
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000a88000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc0000d23c0, 0x38}, 0xc0000fb8d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc0000d23c0, 0x3b}, {{0xc000050540, 0x1, 0x2}, {0xc0000507a0, 0x2, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000abd0, 0x2b}, {{0xc000050540, 0x1, 0x2}, {0xc0000507a0, 0x2, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x134b7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b
```

**Comment by Im-Kal** [comment]
Alright then, already there is a issue for this #1660. Please close this issue

**Comment by AshiePleb** [comment]
I'm having the same issue as above

**Comment by Im-Kal** [comment]
I'm afraid we have to wait for a fix, you can track progress in #1660

**Comment by Im-Kal** [comment]
But for now, here is a [workaround](https://github.com/spicetify/spicetify-cli/issues/1660#issuecomment-1126739949)
