### ISSUE TITLE
There is a problem while installation 

### ISSUE THREAD

**Issue by 0-shubham-0** [spicetify/spicetify-cli#1698]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest 1.1.85.895
- Spicetify version:
```

### 📝 Description

Applying additional modifications:
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc00120a000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc0007c33c0, 0x35}, 0xc0001f18d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc0007c33c0, 0x38}, {{0x6bcff8, 0x0, 0x0}, {0xc00017e180, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000cdb0, 0x28}, {{0x6bcff8, 0x0, 0x0}, {0xc00017e180, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x48b7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b

**Comment by Maxcr1** [comment]
This is a known issue that they are working on. [See this (pinned) thread](https://github.com/spicetify/spicetify-cli/issues/1660)

**Comment by rouzbehzarei** [comment]
> 

I also have this issue which broke Spotify. Now custom theme is applied but extensions page is not loaded and commercials are playing in between songs.
