### ISSUE TITLE
Error loading Marketplace, Reddit or Lyrics page

### ISSUE THREAD

**Issue by PhilRoli** [spicetify/spicetify-cli#1734]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.86.857.g3751ee08 (Windows)
- Spicetify version: 2.10.1
```

### 📝 Description

**Opening the Marketplace, Reddit or Lyrics Sidebar results in a "Something went wrong. Try reloading the page" error.**

Clicking the "Reload Page" Button just reloads the app, resulting in the same error.

For the Marketplace it seems to be because of 
```js
TypeError: Cannot read properties of undefined (reading 'createPortal')
    at TabBarContext (spicetify-routes-spicetify-marketplace.js:1627:21)
```

For Reddit it seem to be because of 
```js
TypeError: Cannot read properties of undefined (reading 'createPortal')
    at TabBarContext (spicetify-routes-reddit.js:899:21)
```

For Lyrics it seems to be because of
```js
TypeError: Cannot read properties of undefined (reading 'createPortal')
    at TabBarContext (spicetify-routes-lyrics-plus.js:2059:21)
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/68249803/171043894-7ab1428d-9d53-4d4f-a0c2-f7a4ceb4f063.png)
Error Page

![image](https://user-images.githubusercontent.com/68249803/171044000-0ec6168f-2f7b-48f8-baf4-ff767445947f.png)
Marketplace

![image](https://user-images.githubusercontent.com/68249803/171044045-c14134d9-9fcb-4199-8811-4a0c11ef9795.png)
Reddit

![image](https://user-images.githubusercontent.com/68249803/171044070-263ad174-e2e1-4dfd-8f6a-66a7eb8d9f88.png)
Lyrics

**Comment by BitterSweetcandyshop** [comment]
Same issue still after running `spicetify update` @PhilRoli does it work for you now or is it just me?

**Comment by PhilRoli** [comment]
> Same issue still after running `spicetify update` @PhilRoli does it work for you now or is it just me?

I reinstalled Spotify, just ran `spicetify backup apply` and now it works again @BitterSweetcandyshop

**Comment by sjhuang26** [comment]
Just did a clean reinstall of spotify and spicetify followed by `spicetify backup apply`. Same issue on my machine.

**Comment by isXander** [comment]
Obviously didn't fix it very well did you

**Comment by isXander** [comment]
This should be re-opened as it is clear it affecting quite a few people and just isn't fixed.

**Comment by isXander** [comment]
> 1.1.84 may not work correctly with 2.10.1

what version of spotify will work?

**Comment by sjhuang26** [comment]
Downgrading to v2.9.9 should fix the issue. For future reference, here is how I did it:

* `spicetify restore`
* `curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh -s v2.9.9`
* `spicetify backup apply`

This makes the Lyrics tab works for me, and the Marketplace UI loads, though due to an unrelated issue, it's not displaying any extensions at the moment.

**Comment by makeworld-the-better-one** [comment]
@ririxichan is it possible a future release of spicetify can fix this and still work with 1.1.84?
